---
engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc
      extensions:
      - .js
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
          mass_threshold: 120

ratings:
  paths:
  - src/**.js
exclude_paths:
- "test/"
- "node_modules/"
