---
engines:
  eslint:
    enabled: true
    channel: eslint-5
    config:
      extensions:
      - .js
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
          mass_threshold: 120
checks:
  method-lines:
    enabled: true
    config:
      threshold: 40

ratings:
  paths:
  - src/**.js
  -
exclude_paths:
- "test/"
- "docs/"
- "nginx/"
- "build/"
- "node_modules/"
- "config/"
- "static/"
