language: minimal

jobs:
  include:
    - stage: build docker image - base
      if: branch != master
      script:
       - docker build -f Dockerfile -t $REPO .
      after_success:
       - docker login -u $DOCKER_USER -p $DOCKER_PASS
       - docker tag $REPO $DOCKER_USER/$REPO:$TRAVIS_BRANCH
       - docker push $DOCKER_USER/$REPO:$TRAVIS_BRANCH

    - stage: build docker image - latets
      if: branch = master
      script:
        - docker build -f Dockerfile -t $REPO .
      after_success:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker tag $REPO $DOCKER_USER/$REPO:latest
        - docker push $DOCKER_USER/$REPO:latest
