runtime: nodejs8

env_variables:
  THEME: blue

handlers:
- url: /static/css/
  mime_type: text/css
  static_dir: dist/static/css/

- url: /static/js/
  mime_type: text/js
  static_dir: dist/static/js/

- url: /static/img/
  static_dir: dist/static/img/

- url: /static/imgs/
  static_dir: dist/static/imgs/

- url: /static/fonts/
  static_dir: dist/static/fonts/

# site root
- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto