runtime: nodejs8

handlers:
- url: /static/css/
  mime_type: text/css
  static_dir: dist/static/css/
  secure: always
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /static/js/
  mime_type: text/js
  static_dir: dist/static/js/
  secure: always
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /static/img/
  static_dir: dist/static/img/
  secure: always
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /static/imgs/
  static_dir: dist/static/imgs/
  secure: always
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /static/fonts/
  static_dir: dist/static/fonts/
  secure: always
  http_headers:
    Access-Control-Allow-Origin: "*"
# site root
- url: /
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto